version: '3.8'

services:
  pubsub-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: pubsub-server:latest
    container_name: pubsub-server
    ports:
      - "5000:5000"
    environment:
      # Use in-memory database by default
      # To use persistent DB, uncomment and set to a file path
      # DATABASE_FILE: /data/pubsub.db
      RUST_LOG: info
    # Uncomment to use persistent database
    # volumes:
    #   - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - pubsub-network

networks:
  pubsub-network:
    driver: bridge
